name: CI

on:
  pull_request:
  push:
    branches: ['master']
  schedule:
  - cron: '00 01 * * *'

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: docker build .
      working-directory: ./.devcontainer/

  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: dotnet build src/Pfim/Pfim.csproj
    - run: dotnet build src/Pfim.ImageSharp/Pfim.ImageSharp.csproj
    - run: dotnet build src/Pfim.Skia/Pfim.Skia.csproj
    - run: dotnet build src/Pfim.MonoGame/Pfim.MonoGame.csproj
    - run: |
        dotnet test --collect 'Code coverage'
      if: matrix.os == 'windows-latest'
    - run: dotnet test
      if: matrix.os == 'ubuntu-latest'

  netframework:
    name: netframework
    runs-on: 'windows-latest'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - run: nuget restore Pfim.sln
    - run: dotnet build src/Pfim/Pfim.csproj
    - run: dotnet build src/Pfim.Benchmarks/Pfim.Benchmarks.csproj
    - run: msbuild src/Pfim.Viewer.Forms/Pfim.Viewer.Forms.csproj -t:rebuild
    - run: msbuild src/Pfim.Viewer/Pfim.Viewer.csproj -t:rebuild
